# Generated by Django 2.0.4 on 2018-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectblog', '0003_auto_20180501_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
